name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 1 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://tech.kakao.com/feed/,https://tech.kakaopay.com/rss,https://meetup.nhncloud.com/rss,https://techblog.woowahan.com/feed/,https://helloworld.kurly.com/feed,http://feeds2.feedburner.com/rss_outsider_dev"
          max_post_count: 10
          date_format: "UTC:yyyy-mm-dd"
          feed_names: "kakao,kakaopay,NHNCloud,우아한형제들,컬리,Outsider's Dev Story"
          template: '<div>$randomEmoji(:pushpin:)[$feedName] <a target="_blank" href="$url">$title</a> ($date)</div>'
